### ISSUE TITLE
[ERROR] Sync: Can't create new task, 'list' object has no attribute 'replace'

### ISSUE THREAD

**Issue by MuhAssar** [mrvladus/Errands#244]
I'm using errands with nextcloud sync enabled.

I added a new task using the nextcloud web interface, but it is not shoing in errands, and the console prints the following logs:

```
[INFO] Sync: Connected to Nextcloud server at 'https://use09.thegood.cloud/remote.php/dav/'
[INFO] Sync: Sync tasks with remote
[DEBUG] Sync: Delete local list deleted on remote 'cb6b6fb8-d3af-4aa1-829f-2f404b9408da'
[DEBUG] Sync: Getting tasks for None
[DEBUG] Sync: Copy list from remote None
[DEBUG] Data: Create '586b1f0a-57ff-4bdc-b196-8744dd33dd6c' list
[DEBUG] Sync: Create new task on remote: 76f1bb0d-d8f9-45c8-a576-d091a39b336b
[ERROR] Sync: Can't create new task on remote: 76f1bb0d-d8f9-45c8-a576-d091a39b336b
'list' object has no attribute 'replace'
[DEBUG] Sync: Create new task on remote: 8b4902cf-3a6b-4ad4-b51e-be1a2e23128f
[ERROR] Sync: Can't create new task on remote: 8b4902cf-3a6b-4ad4-b51e-be1a2e23128f
'list' object has no attribute 'replace'
[DEBUG] Sync: Copy new task from remote to list 'None': 405faa63-ee71-43ad-908c-ef3038887c6c
[DEBUG] Data: Add task 405faa63-ee71-43ad-908c-ef3038887c6c
Exception in thread Thread-1 (sync):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/errands/errands/lib/sync/sync.py", line 67, in sync
    self.provider.sync()
  File "/usr/share/errands/errands/lib/sync/providers/caldav.py", line 398, in sync
    UserData.add_task(
  File "/usr/share/errands/errands/lib/data.py", line 358, in add_task
    cur.execute(
sqlite3.IntegrityError: NOT NULL constraint failed: tasks.list_uid
```

**Comment by mrvladus** [comment]
I've released new version on flathub, can you try it and see if bug was fixed?

**Comment by MuhAssar** [comment]
yes it is fixed in the new version, thanks
