### ISSUE TITLE
Cannot configure sync, gi.repository.GLib.GError: g-io-error-quark: user interaction failed (0)

### ISSUE THREAD

**Issue by v6ak** [mrvladus/Errands#330]
## Environment

* Fedora 40 / Debian 12, virtualized in Qubes OS
* Flatpak
* X11

## Reproduction

1. Freshly install Errands
2. Configure sync – use CalDAV
3. Test Connection
4. Exit settings

## Expected results

1. Errands contacts the server to test the connection
2. Connection details are stored

## Actual results

1. No connection attempt is made. (Verified with Wireshark.)
2. I can no longer open settings
3. Errands shows the following error in console:

```
Traceback (most recent call last):
  File "/app/share/errands/errands/widgets/preferences.py", line 130, in <lambda>
    self.sync_providers.connect("notify::selected", lambda *_: self._setup_sync())
                                                               ^^^^^^^^^^^^^^^^^^
  File "/app/share/errands/errands/widgets/preferences.py", line 195, in _setup_sync
    password: str = GSettings.get_secret(account)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/errands/errands/lib/gsettings.py", line 47, in get_secret
    return Secret.password_lookup_sync(SECRETS_SCHEMA, {"account": account}, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: user interaction failed (0)
Traceback (most recent call last):
  File "/app/share/errands/errands/widgets/preferences.py", line 130, in <lambda>
    self.sync_providers.connect("notify::selected", lambda *_: self._setup_sync())
                                                               ^^^^^^^^^^^^^^^^^^
  File "/app/share/errands/errands/widgets/preferences.py", line 195, in _setup_sync
    password: str = GSettings.get_secret(account)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/errands/errands/lib/gsettings.py", line 47, in get_secret
    return Secret.password_lookup_sync(SECRETS_SCHEMA, {"account": account}, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: user interaction failed (0)


```

**Comment by mrvladus** [comment]
Do you have `libsecret` installed? Seems like it errors when trying to call libsecret function
