### ISSUE TITLE
Issue syncing with CalDAV

### ISSUE THREAD

**Issue by lokesh-krishna** [mrvladus/Errands#364]
On Errands 46.2.6 on Arch Linux. Trying to sync with a locally running CalDAV server which in turn syncs with EteSync. The connection test is successful but this is what I get when it's actually syncing.

Could you please guide me on how to troubleshoot?

```
[INFO] Sync: Sync tasks with remote
Exception in thread Thread-1 (sync):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/errands/errands/lib/sync/sync.py", line 53, in sync
    self.provider.sync()
  File "/usr/share/errands/errands/lib/sync/providers/caldav.py", line 215, in sync
    self.__sync_lists()
  File "/usr/share/errands/errands/lib/sync/providers/caldav.py", line 235, in __sync_lists
    self.__update_local_list(cal, list)
  File "/usr/share/errands/errands/lib/sync/providers/caldav.py", line 298, in __update_local_list
    color = cal.get_property(caldav.elements.ical.CalendarColor())
                             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'caldav.elements' has no attribute 'ical'
```

**Comment by lokesh-krishna** [comment]
I think it's the same issue as here? 
[Python-Caldav Issue #98](https://github.com/python-caldav/caldav/issues/98)

Seems like the solution is importing `caldav.elements.ical`.

**Comment by lokesh-krishna** [comment]
Was using the Arch Linux package but this is not an issue with the Flatpak. Should I close the issue?

**Comment by mrvladus** [comment]
I can't controll dependecies on arch linux unlike flatpak, that is why it's not supported by me, but I just released new version and it should work on arch now.
