### ISSUE TITLE
When syncing tasks from a radicale server to errands through webdav it shows  sqlite3.IntegrityError: NOT NULL constraint failed: tasks.list_uid

### ISSUE THREAD

**Issue by joanisc** [mrvladus/Errands#368]
Steps to reproduce:
1) Configure a new webdav tasks calendar
2) Click on sync

Expected:
Tasks appear in errands

Actual:
The following error appears:

[DEBUG] Data: Add task 372bc905-0949-4284-8aa3-f5ef185a0e2a
Exception in thread Thread-1 (sync):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/errands/errands/lib/sync/sync.py", line 67, in sync
    self.provider.sync()
  File "/usr/share/errands/errands/lib/sync/providers/caldav.py", line 398, in sync
    UserData.add_task(
  File "/usr/share/errands/errands/lib/data.py", line 358, in add_task
    cur.execute(
sqlite3.IntegrityError: NOT NULL constraint failed: tasks.list_uid

**Comment by mrvladus** [comment]
Are you using old version of the app? Please use [flatpak](https://flathub.org/apps/io.github.mrvladus.List). Other packages are not official and not supported because they can be very outdated.

**Comment by joanisc** [comment]
> Are you using old version of the app? Please use [flatpak](https://flathub.org/apps/io.github.mrvladus.List). Other packages are not official and not supported because they can be very outdated.

Thank you! With the version from flatpak it worked fine! I thought that the errands version from the last ubuntu stable should be ok! I close the issue.
